"use strict";
exports.__esModule = true;
var ContractEmployee_1 = require("./ContractEmployee");
var FulltimeEmployee_1 = require("./FulltimeEmployee");
var Salary_1 = require("./Salary");
var emp_1 = new ContractEmployee_1["default"]('Mai');
var emp_2 = new ContractEmployee_1["default"]('Binh');
var emp_3 = new FulltimeEmployee_1["default"]('Ti');
var emp_4 = new FulltimeEmployee_1["default"]('Linh');
var emp_5 = new FulltimeEmployee_1["default"]('Co');
var employeeList;
employeeList = [emp_1, emp_2, emp_3, emp_4, emp_5];
console.log("Sum salary: ".concat((0, Salary_1.sumSalary)(employeeList)));
console.log('================================');
console.log((0, Salary_1.minMaxSalary)(employeeList));
console.log('================================');
console.log('Sort by salary:');
(0, Salary_1.sortBySalary)(employeeList);
console.log('================================');
console.log('Sort by name:');
(0, Salary_1.sortByName)(employeeList);
